[build]
  command = "./src/build.sh"
  publish = "site"

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200


# [[redirects]]
#   from = "/index.html"
#   to = "/"
#   status = 301
